In [8]:
import numpy as np

## Create array using numpy
# Create a 1D array

arr1 = np.array([1,2,3,4,5])

print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.size) # no. of elements
print(arr1.ndim) # no.of dimension
print(arr1.dtype) # data type
print(arr1.itemsize) #itemsize in bytes

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
5
1
int64
8


In [4]:
arr2 = np.array([1,2,3,4,5])

arr2.reshape(1,5) ## 1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [5]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])

print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
## numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition : ",arr1+arr2)

## Element wise Subtraction
print("Subtraction : ",arr1-arr2)


Addition :  [11 22 33 44 55]
Subtraction :  [ -9 -18 -27 -36 -45]


In [11]:
## universal Function 

arr = np.array([2,3,4,5])\

## Square root 
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

## natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798]
[  7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.69314718 1.09861229 1.38629436 1.60943791]


In [13]:
# array slicing and indexing 

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
arr[0]

array([1, 2, 3, 4])

In [15]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [16]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [18]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [19]:
## Modify array elements

arr[0,0] = 100

print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [22]:
## Statistical concept normalization
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)
variance = np.var(data)
median = np.median(data)
normalized_data = (data-mean)/std_dev

print("Noralized Data : ",normalized_data)

Noralized Data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [23]:
print(mean)
print(median)
print(variance)

3.0
3.0
2.0


In [28]:
## logical operations 

data = np.array([1,2,3,4,5,6,7,8,9,10])

data [(data>=5) & (data<=8)]

array([5, 6, 7, 8])